# Generated by Django 4.2.9 on 2024-01-10 05:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_writer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='comments',
            field=jsonfield.fields.JSONField(default={'': ''}),
        ),
    ]
