# Generated by Django 4.2.9 on 2024-01-10 05:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='comments',
            field=jsonfield.fields.JSONField(verbose_name=jsonfield.fields.JSONField()),
        ),
    ]
