# Generated by Django 4.2.9 on 2024-01-12 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='writer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 12)),
        ),
    ]
