# Generated by Django 4.2.9 on 2024-01-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default='', upload_to='users/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
