# Generated by Django 4.2.9 on 2024-01-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_writer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
